<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="inverted_pendulum">
    <!-- base_link -->
    <xacro:property name="base_length" value="1"/>
    <xacro:property name="base_width" value="0.1"/>
    <xacro:property name="base_height" value="0.5"/>
    
    <link name="world">
    </link>
    <link name="base">
        <visual>
            <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 1.0 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="base2world" type="fixed">
        <parent link="world"/>
        <child link="base"/>
        <origin xyz="0.0 0.0 ${base_height / 2}" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>